This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./bryant_comp_sys.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file bryant_comp_sys.acn....done (11 entries accepted, 0 rejected).
Sorting entries....done (47 comparisons).
Generating output file bryant_comp_sys.acr....done (30 lines written, 0 warnings).
Output written in bryant_comp_sys.acr.
Transcript written in bryant_comp_sys.alg.
